MCU_SERIES = m33
MCU_VARIANT = nrf91
MCU_SUB_VARIANT = nrf9160
LD_FILES += boards/nrf9160_1M_256k.ld

DFU ?= 1

ifeq ($(DFU),1)
BOOTLOADER=mcuboot
BOOTLOADER_VERSION=1.0
FLASHER=mcumgr
endif

NRF_DEFINES += -DNRF9160_XXAA -DNRF_TRUSTZONE_NONSECURE 
